-- MySQL Script generated by MySQL Workbench
-- Mon Jun  8 15:25:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`Catégories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`Catégories` (
  `id_Catégorie` INT NOT NULL AUTO_INCREMENT,
  `nom_Catégorie` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Catégorie`),
  UNIQUE INDEX `nom_Catégorie_UNIQUE` (`nom_Catégorie` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`Villes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`Villes` (
  `id_Ville` INT NOT NULL AUTO_INCREMENT,
  `nom_Ville` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Ville`),
  UNIQUE INDEX `nom_Ville_UNIQUE` (`nom_Ville` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`Spécialités`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`Spécialités` (
  `id_Spécialité` INT NOT NULL AUTO_INCREMENT,
  `nom_Spécialité` VARCHAR(45) NULL,
  `Catégories_id_Catégorie` INT NULL,
  PRIMARY KEY (`id_Spécialité`),
  UNIQUE INDEX `nom_Spécialité_UNIQUE` (`nom_Spécialité` ASC) ,
  KEY `fk_Spécialités_Catégories1_idx` (`Catégories_id_Catégorie` ASC) ,
  CONSTRAINT `fk_Spécialités_Catégories1`
    FOREIGN KEY (`Catégories_id_Catégorie`)
    REFERENCES `db`.`Catégories` (`id_Catégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`Top`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`Top` (
  `id_Top` INT NOT NULL AUTO_INCREMENT,
  `top_Value` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Top`),
  UNIQUE INDEX `top_Value_UNIQUE` (`top_Value` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`Artisans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`Artisans` (
  `id_Artisan` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `site_web` VARCHAR(45) NULL DEFAULT NULL,
  `a_propos` VARCHAR(255) NULL,
  `photo_url`VARCHAR(255) NULL,
  `note` DECIMAL(2,1) NOT NULL,
  `Spécialités_id_Spécialité` INT NULL,
  `Villes_id_Ville` INT NULL,
  `Top_id_Top` INT NULL,
  PRIMARY KEY (`id_Artisan`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `site_web_UNIQUE` (`site_web` ASC) ,
  UNIQUE INDEX `photo_url_UNIQUE`(`photo_url`ASC),
  KEY `fk_Artisan_Spécialités_idx` (`Spécialités_id_Spécialité` ASC) ,
  KEY `fk_Artisans_Villes1_idx` (`Villes_id_Ville` ASC) ,
  KEY `fk_Artisans_Top1_idx` (`Top_id_Top` ASC) ,
  CONSTRAINT `fk_Artisan_Spécialités`
    FOREIGN KEY (`Spécialités_id_Spécialité`)
    REFERENCES `db`.`Spécialités` (`id_Spécialité`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artisans_Villes1`
    FOREIGN KEY (`Villes_id_Ville`)
    REFERENCES `db`.`Villes` (`id_Ville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artisans_Top1`
    FOREIGN KEY (`Top_id_Top`)
    REFERENCES `db`.`Top` (`id_Top`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
